### ISSUE TITLE
kubernetes helm chart: Automatically assign an ordinal index from statefulsets metadata

### ISSUE THREAD

**Issue by weideng1** [datastax/zdm-proxy#88]
Currently zdm-proxy process expects this env value to be set at start time: `ZDM_PROXY_TOPOLOGY_INDEX`

I've looked into online discussions, and looks like there is an unresolved issue w.r.t. directly exposing this ordinal index from statefulsets: https://github.com/kubernetes/kubernetes/issues/40651

Before this is fully supported in a future version of k8s, we will have to adopt some ugly workaround by either using initContainers or lifecycle hook like the following:

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  serviceName: "zdm-proxy"
  replicas: {{ $.Values.proxy.count | int }}
  template:
    spec:
      containers:
      - lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export STS_INDEX=${HOSTNAME##*-}"]
```
